version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: selenium/node-chrome # circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
